import { useState } from 'react';
import { AlertTriangle, BarChart3, Bell, CalendarCheck, CalendarDays, Car, ClipboardList, CreditCard, Home, LogOut, MapPin, Moon, PanelLeftClose, PanelLeftOpen, Radio, Settings, Star, Sun, Timer, Users, Wrench } from 'lucide-react';
import './Dashboard.css';

const navGroups = [
	['Workspace', ['Dashboard', 'Customers', 'Trust Scoreboard', 'Bookings', 'Payments', 'Vehicles', 'Vehicle Availability']],
	['Monitor', ['Rental Monitoring', 'IoT Monitoring', 'Collision Alerts', 'Vehicle Health', 'Extensions']],
	['Manage', ['Notifications', 'Reports', 'Audit Logs', 'Settings']],
];
const navIcons = {
	Dashboard: Home,
	Customers: Users,
	'Trust Scoreboard': Star,
	Bookings: CalendarDays,
	Payments: CreditCard,
	Vehicles: Car,
	'Vehicle Availability': CalendarCheck,
	'Rental Monitoring': MapPin,
	'IoT Monitoring': Radio,
	'Collision Alerts': AlertTriangle,
	'Vehicle Health': Wrench,
	Extensions: Timer,
	Notifications: Bell,
	Reports: BarChart3,
	'Audit Logs': ClipboardList,
	Settings,
};
const counts = { Bookings: 8, Payments: 4, 'Collision Alerts': 2, Extensions: 3 };
const bookings = [
	['BK-2056', 'Amelia Morgan', 'Tesla Model 3', 'Oct 16 - 19', '$540.00', 'Pending'],
	['BK-2053', 'Daniel Kim', 'Honda CR-V', 'Oct 18 - 22', '$420.00', 'Awaiting payment'],
	['BK-2051', 'Lucas Pereira', 'Volvo XC40', 'Oct 15 - 17', '$360.00', 'Confirmed'],
	['BK-2048', 'Priya Shah', 'Toyota RAV4', 'Oct 14 - 16', '$280.00', 'Active'],
];

export default function Dashboard({ user, onLogout, theme, onToggleTheme }) {
	const [view, setView] = useState('Dashboard');
	const [mobileOpen, setMobileOpen] = useState(false);
	const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
	const [toast, setToast] = useState('');
	const [reviewOpen, setReviewOpen] = useState(false);
	const notify = (message) => { setToast(message); window.clearTimeout(window.arcToast); window.arcToast = window.setTimeout(() => setToast(''), 2400); };
	const selectView = (next) => { setView(next); setMobileOpen(false); if (next !== 'Dashboard') notify(`${next} workspace selected`); };

	return <main className={`admin-shell ${sidebarCollapsed ? 'sidebar-collapsed' : ''}`}><aside className={mobileOpen ? 'open' : ''}><div className="side-brand"><div className="brand-lockup"><strong>ARC RIDE</strong><span>DAVAO RENT A CAR</span></div><button className="collapse-side" onClick={() => setSidebarCollapsed((collapsed) => !collapsed)} aria-label={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'} title={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{sidebarCollapsed ? <PanelLeftOpen aria-hidden="true" /> : <PanelLeftClose aria-hidden="true" />}</button><button className="close-side" onClick={() => setMobileOpen(false)}>×</button></div><nav>{navGroups.map(([group, items]) => <div key={group}><p className="nav-label">{group}</p>{items.map((item) => { const Icon = navIcons[item]; return <button key={item} className={view === item ? 'selected' : ''} onClick={() => selectView(item)} title={sidebarCollapsed ? item : undefined}><Icon aria-hidden="true" /><span className="nav-text">{item}</span>{counts[item] && <b>{counts[item]}</b>}</button>; })}</div>)}</nav><div className="account"><span>AH</span><div className="account-details"><strong>{user.name}</strong><small>{user.role}</small></div></div><button className="logout" onClick={onLogout} title="Sign out"><span className="logout-icon"><LogOut aria-hidden="true" /></span><span className="logout-text">Sign out</span></button></aside><section className="admin-main"><header className="admin-header"><button className="menu" onClick={() => setMobileOpen(true)}>☰</button><div><span className="crumb">ARC Operations / </span><strong>{view}</strong></div><div className="header-actions"><button className="theme-toggle header-theme-toggle" onClick={onToggleTheme} aria-label="Toggle theme">{theme === 'light' ? <Moon aria-hidden="true" /> : <Sun aria-hidden="true" />}</button><button className="notification-button" onClick={() => notify('Notifications are up to date')} aria-label="Notifications"><Bell aria-hidden="true" /></button><button className="profile" onClick={onLogout}>AH</button></div></header><div className="content"><div className="title-row"><div><p className="eyebrow">MONDAY, 14 OCTOBER 2024 · LIVE OPERATIONS</p><h1>{view === 'Dashboard' ? 'Good morning, Ariel' : view}</h1><p className="muted">{view === 'Dashboard' ? 'Here’s what’s happening across your fleet today.' : description(view)}</p></div><button className="primary compact" onClick={() => notify(view === 'Dashboard' ? 'New booking flow opened' : `${view} action opened`)}>＋ {view === 'Dashboard' ? 'New booking' : 'Create new'}</button></div>{view === 'Dashboard' ? <Overview onNotify={notify} onReview={() => setReviewOpen(true)} /> : <Workspace view={view} onNotify={notify} />}</div></section>{toast && <div className="toast">{toast}</div>}{reviewOpen && <ReviewModal onClose={() => setReviewOpen(false)} onSave={() => { setReviewOpen(false); notify('Customer review note saved'); }} />}</main>;
}

function Overview({ onNotify, onReview }) { return <><section className="stat-grid">{[['Fleet vehicles', '42', '30 available today'], ['Active rentals', '18', '4 due back today'], ['Upcoming pickups', '07', 'Next: 09:30 today'], ['Needs attention', '06', '2 suspected impacts']].map(([label, value, note]) => <article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><section className="overview-grid"><article className="panel"><PanelTitle title="Revenue overview" subtitle="Gross revenue from completed and active rentals" /><div className="revenue">$24,680 <em>↗ 14.8%</em></div><div className="bars">{[38, 54, 46, 72, 62, 88, 78, 95, 82, 100].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><div className="chart-labels"><span>Sep 16</span><span>Sep 30</span><span>Oct 14</span></div></article><article className="panel"><PanelTitle title="Priority alerts" subtitle="Items requiring your attention" action="View all" /><Alert title="Suspected impact detected" detail="VH-027 · Active rental · 8 min ago" tone="critical" onClick={() => onNotify('Impact alert acknowledged')} /><Alert title="Payment verification pending" detail="BK-2053 · $420.00 · 24 min ago" tone="warning" onClick={() => onNotify('Payment review opened')} /><Alert title="Extension request received" detail="BK-2031 · 2 additional days" tone="info" onClick={() => onNotify('Extension request opened')} /></article></section><section className="panel table-panel"><PanelTitle title="Recent bookings" subtitle="Latest activity across your rental operations" action="View all bookings" /><Table /></section><section className="quick-grid"><button className="quick-card" onClick={onReview}><span>✦</span><strong>Trust scoreboard</strong><small>Review customer behavior and rental compliance</small></button><button className="quick-card" onClick={() => onNotify('Collision alert workflow opened')}><span>⚠</span><strong>Collision alerts</strong><small>Investigate suspected impacts with an audit trail</small></button><button className="quick-card" onClick={() => onNotify('Availability calendar opened')}><span>▦</span><strong>Vehicle availability</strong><small>See reserved, active, maintenance, and open periods</small></button></section></>; }
function PanelTitle({ title, subtitle, action }) { return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <button className="link-button">{action} →</button>}</div>; }
function Alert({ title, detail, tone, onClick }) { return <div className="alert-row"><span className={`alert-dot ${tone}`}>!</span><div><strong>{title}</strong><small>{detail}</small></div><button onClick={onClick}>···</button></div>; }
function Table() { return <div className="table-scroll"><table><thead><tr><th>BOOKING</th><th>CUSTOMER</th><th>VEHICLE</th><th>DATES</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{bookings.map(([id, customer, vehicle, dates, amount, status]) => <tr key={id}><td><b>{id}</b><small>Created recently</small></td><td>{customer}</td><td>{vehicle}</td><td>{dates}</td><td>{amount}</td><td><span className={`status ${status.replaceAll(' ', '-').toLowerCase()}`}>{status}</span></td></tr>)}</tbody></table></div>; }
function Workspace({ view, onNotify }) { const rows = view === 'Customers' || view === 'Trust Scoreboard' ? [['Amelia Morgan', 'Excellent', '8 rentals', '100% on-time'], ['Daniel Kim', 'Good', '5 rentals', '92% on-time'], ['Marcus Cole', 'Review Needed', '3 rentals', '67% on-time']] : view === 'Vehicles' || view === 'Vehicle Availability' || view === 'Vehicle Health' ? [['VH-027', 'Toyota RAV4', 'Active rental', 'Connected'], ['VH-018', 'Kia Sportage', 'Inspection due', 'Connected'], ['VH-031', 'Tesla Model 3', 'Available', 'Connected']] : [['BK-2056', 'Amelia Morgan', 'Tesla Model 3', 'Pending'], ['BK-2053', 'Daniel Kim', 'Honda CR-V', 'Awaiting payment'], ['BK-2048', 'Priya Shah', 'Toyota RAV4', 'Active']]; return <section className="workspace"><div className="filter-row"><input placeholder={`Search ${view.toLowerCase()}...`} /><select><option>All statuses</option><option>Needs attention</option><option>Active</option></select><button className="secondary" onClick={() => onNotify('Filters applied')}>Filter</button></div><div className="panel"><PanelTitle title={`${view} records`} subtitle="Live records from the shared ARC rental backend" /><div className="record-grid">{rows.map((row) => <article className="record" key={row[0]}><div><strong>{row[0]}</strong><small>{row[1]}</small></div><span>{row[2]}</span><b>{row[3]}</b><button onClick={() => onNotify(`${row[0]} details opened`)}>View →</button></article>)}</div></div><div className="panel policy"><p className="eyebrow">RENTAL POLICY WORKFLOW</p><h2>Normal → Warning → Admin Review → Controlled Restriction Eligible → Resolved</h2><p className="muted">Any restriction request requires authorization, safety checks, audit logging, and a recovery path. No abrupt engine shutdown while moving.</p></div></section>; }
function ReviewModal({ onClose, onSave }) { return <div className="modal-layer"><div className="modal"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">CUSTOMER REVIEW</p><h2>Amelia Morgan</h2><div className="score"><strong>92</strong><span><b>Excellent</b><small>Trust score · explainable indicators</small></span></div><div className="reasons"><span>✓ 8 completed rentals</span><span>✓ 100% on-time returns</span><span>✓ No verified incidents</span></div><label>Admin note</label><textarea placeholder="Add context for your team..." /><button className="primary" onClick={onSave}>Save review note</button></div></div>; }
function description(view) { return { Customers: 'Search customer profiles, booking history, payment records, and rental behavior.', 'Trust Scoreboard': 'Review transparent trust indicators without automatically rejecting customers.', Bookings: 'Track pending, payment, confirmed, active, completed, cancelled, and extension states.', Payments: 'Verify in-person payments and update booking confirmation.', Vehicles: 'Manage vehicle details, publishing, availability, maintenance, and IoT assignments.', 'Vehicle Availability': 'Calendar view for reserved, active rental, maintenance, and unavailable periods.', 'Rental Monitoring': 'Monitor upcoming pickups, returns, locations, and operational reminders.', 'IoT Monitoring': 'Review connected vehicle devices, communication time, impact status, and severity.', 'Collision Alerts': 'Investigate suspected impacts; sensor events are not absolute proof of damage.', 'Vehicle Health': 'Review connectivity, collision incidents, maintenance, inspections, and event timeline.', Extensions: 'Approve or reject requested dates, cost estimates, and vehicle availability.', Notifications: 'Centralized alerts for collisions, payments, pickups, returns, extensions, and maintenance.', Reports: 'Bookings, revenue, utilization, duration, trust trends, incidents, and availability.', 'Audit Logs': 'Trace payment verification, record changes, status updates, and restriction requests.', Settings: 'Manage roles, permissions, IoT settings, reminders, trust configuration, and preferences.' }[view] || 'Manage ARC rental operations.'; }
